name: Deploy CloudFormation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      
      - name: Debug Files
        run: |
          echo "Current Path:"
          pwd
          echo "All Files:"
          ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template/CloudFormation-infrastructure-deploy-aws.yml \
            --stack-name hospital-stack \
            --parameter-overrides HospitalId=med123 Environment=dev \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get Stack Events
        if: failure()
        run: |
            aws cloudformation describe-stack-events \
            --stack-name hospital-stack \
            --max-items 20