name: Deploy CloudFormation

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: "Enter Stack Name"
        required: true
        default: "hospital-stack"

      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
        default: dev
               

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      
      - name: Delete Old Stack (if exists)
        run: |
            aws cloudformation delete-stack --stack-name ${{ github.event.inputs.stack_name }} || true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
          --template-file template/CloudFormation-infrastructure-deploy-aws.yml \
          --stack-name ${{ github.event.inputs.stack_name }} \
          --parameter-overrides \
          HospitalId=${{ github.event.inputs.stack_name }} \
          Environment=${{ github.event.inputs.environment }} \
          DBPassword=${{ secrets.DB_PASSWORD }} \
          --capabilities CAPABILITY_NAMED_IAM

      - name: Get Stack Events
        if: failure()
        run: |
            aws cloudformation describe-stack-events \
            --stack-name hospital-stack \
            --max-items 20